### ISSUE TITLE
rich presence not showing up

### ISSUE THREAD

**Issue by weegeedoescoding** [Rarcoon/Discord-Rich-Presence-Tool#10]
why isn't the rich presence showing up even when i start it up?

**Comment by Rarcoon** [comment]
Hi, make sure you're using the latest version of DRPT (v1.0.2), as previous versions no longer work due to the associated Discord developer account being deleted.

If you're already using the latest version of DRPT, please let me know which Discord client and operating system you are using!

**Comment by weegeedoescoding** [comment]
hmmm ok then thanks!
