### ISSUE TITLE
Compiling on Linux?

### ISSUE THREAD

**Issue by waterlubber** [Rarcoon/Discord-Rich-Presence-Tool#6]
I'm trying to compile this on my Linux Mint machine, but get the following error: 
```
 waterlubber@gamingPC  ~/.local/share/discordRPT/drpt   master  qmake -project
 waterlubber@gamingPC  ~/.local/share/discordRPT/drpt   master  qmake
 waterlubber@gamingPC  ~/.local/share/discordRPT/drpt   master  make
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o aboutdialog.o aboutdialog.cpp
In file included from aboutdialog.cpp:1:0:
aboutdialog.h:3:19: fatal error: QDialog: No such file or directory
compilation terminated.
Makefile:376: recipe for target 'aboutdialog.o' failed

```

I've never worked with qt development before, do you know what dependencies I should look for or use?
Thanks.

**Comment by ionadev** [comment]
I Would like updates on this too!

**Comment by ionadev** [comment]
Uh Any updates? @Rarcoon

**Comment by Rarcoon** [comment]
Hi, sorry for the super late reply!

I've recently refactored the project to use Qt Creator instead of Visual Studio. At the time of posting this comment, the project currently isn't set up to compile for Linux. However, you should be able to add additional Linux-specific options to the Qt project file to compile on Linux.

**Comment by officialpiyush** [comment]
So you mean there would be no solution from your side?

**Comment by undevdecatos** [comment]
install qt5-dialog

**Comment by undevdecatos** [comment]
in your distro
