### ISSUE TITLE
Would it be possible to use our own dev account and application with it?

### ISSUE THREAD

**Issue by lrmtheboss** [Rarcoon/Discord-Rich-Presence-Tool#8]
I do have my own dev app setup for my custom rich presence, so I would prefer to use my own.
I have seen where you talk about recompiling it with your own dev app, but I have no idea on how to do this.

Thanks,
LRM

**Comment by tony-codes** [comment]
@lrmtheboss
Hi, 
I attached working project that was rebuilt from original one using Visual Studio 19 Community Version. I used my own key from Discord Dev site. You may need to download additional dependencies to make it buildable for you (I have included some Qt libs inside `~\Discord-Rich-Presence-Tool-1.0.2\x64\Release`), I recommend installing:
- Qt plugin for MS Visual Studio 19 - looks like I don't even need it to build.
![obrázok](https://user-images.githubusercontent.com/49917946/91971618-ca2af680-ed19-11ea-8744-70b691e7a1d6.png)
- Qt plugin - standalone installation
- Windows SDKit
If you try to build and miss some files, use google to locate tools that provide you with specific missing files needed to build the project. I might later edit this as I don't remember build errors I have encountered.
**Very important files I had to modify to be able to use Qt are in these directories (normal & backup):**
`~\Discord-Rich-Presence-Tool-1.0.2\backup`
You may only need to edit normal project files (2 files with the same name as in backup folder) with e.g. Notepad++ using search feature:
`~\Discord-Rich-Presence-Tool-1.0.2\drpt` .

**Last notable updates for Discord Devs:** Discord API migrates from discordapp.com --> discord.com 
https://www.reddit.com/r/discordapp/comments/hsyv58/i_got_a_message_today_from_discord/
![obrázok](https://user-images.githubusercontent.com/49917946/91972862-92bd4980-ed1b-11ea-9dfb-fbbe994b2d36.png)

I wanted to respond earlier, if you have any questions feel free to ask.
Note: I deleted `.vs` folder with IntelliSense precompiled headers(`*.ipch` files) (quite volumetric - 700 MBs)

**Access my modifed build as zip at:**
[Discord-RP-Tool-1.0.2_rebuilt.zip](https://github.com/Rarcoon/Discord-Rich-Presence-Tool/files/5162012/Discord-RP-Tool-1.0.2_rebuilt.zip)
