### ISSUE TITLE
Custom avatar

### ISSUE THREAD

**Issue by ApexRP** [Rarcoon/Discord-Rich-Presence-Tool#9]
Would be pretty sick to use custom images somehow mby use a link or drop them in folder have the software have a refresh to know if there is more pics or less like a refresh to know if somethings there or not

**Comment by cjwswim** [comment]
I don't know how to do this, but all you would have to do is somehow add the pictures yourself in the resource files.

**Comment by TheRedrex07** [comment]
when will get the option to add custom pics ?

**Comment by yumyum0** [comment]
> when will get the option to add custom pics ?

I don't know, maybe you can help us.

**Comment by ApexRP** [comment]
Will it depends on Rarcoon imo would be lit tho :)
